name: test
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
    tags-ignore:
      - "*"

jobs:
  test:
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    env:
      RUST_BACKTRACE: "full"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - name: Install dependencies and set OS environment variable
        env:
          DEBIAN_FRONTEND: "noninteractive"
        run: |
          sudo apt update && sudo apt install -y libdbus-1-dev gnome-keyring dbus-x11 libssl-dev
        if: runner.os == 'Linux'
      - name: Test on Linux
        if: runner.os == 'Linux'
        run: |
          cargo fmt -- --check
          cargo clippy --release
          ci/test.sh
      - name: Test on Windows/macOS
        if: runner.os != 'Linux'
        run: |
          cargo fmt -- --check
          cargo clippy --release
          cargo test --release --locked
