name: test
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
    tags-ignore:
      - "*"

jobs:
  test:
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - name: Install dependencies and set OS environment variable
        run: |
          sudo apt-get install -y libdbus-1-dev gnome-keyring dbus-x11 libssl-dev
          echo "GITHUB_ACTIONS_OS=linux" >> $GITHUB_ENV
        if: runner.os == 'Linux'
      - name: Build
        env:
          RUST_BACKTRACE: "full"
          GITHUB_ACTIONS_OS: "${{ env.GITHUB_ACTIONS_OS }}"
        run: |
          cargo fmt -- --check
          cargo clippy --release
          ci/test.sh
